# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "196d59e1853acf9349babc6e7efda370"
name = "app-billing-shop"
handle = "app-billing-shop"
application_url = "https://billing-app-shop.vercel.app/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_billing,read_billing"

[auth]
redirect_urls = [
  "https://billing-app-shop.vercel.app/auth/callback",
  "https://billing-app-shop.vercel.app/auth/shopify/callback",
  "https://billing-app-shop.vercel.app/api/auth/callback"
]

[pos]
embedded = false
